Add ui component to DG
AY1920S2-CS2113-T14-1/tp pull request #139
Opened 2020-03-30 14:25 UTC by sliu107

2020-03-30 15:18 UTC, Zhilin-Huang requested changes
![image](https://user-images.githubusercontent.com/31772358/77929622-746ea000-72dc-11ea-8010-2de8a9c43758.png)
Hmmmm The links seem to be broken?

2020-03-31 02:24 UTC, sliu107 commented
> ![image](https://user-images.githubusercontent.com/31772358/77929622-746ea000-72dc-11ea-8010-2de8a9c43758.png)
> Hmmmm The links seem to be broken?

It's weird. The links look well on my own repo.
![tp_DeveloperGuide md at add-ui-component-to-DG · sliu107_tp](https://user-images.githubusercontent.com/59828791/77980300-87fc2400-7339-11ea-92ef-341e94548ff2.jpg)

2020-03-31 03:45 UTC, Zhilin-Huang commented
> > ![image](https://user-images.githubusercontent.com/31772358/77929622-746ea000-72dc-11ea-8010-2de8a9c43758.png)
> > Hmmmm The links seem to be broken?
> 
> It's weird. The links look well on my own repo.
> ![tp_DeveloperGuide md at add-ui-component-to-DG · sliu107_tp](https://user-images.githubusercontent.com/59828791/77980300-87fc2400-7339-11ea-92ef-341e94548ff2.jpg)

Maybe it's because it has not been merged yet, I think we can merge and check :)

2020-03-31 03:45 UTC, Zhilin-Huang approved these changes

2020-03-31 03:47 UTC, merged