update add flashcard  to group command
AY1920S2-CS2113-T14-1/tp pull request #183
Opened 2020-04-07 09:49 UTC by sliu107

… index

2020-04-07 15:24 UTC, g-lilian approved these changes
Looks good, perhaps you can update text-ui-test as well? By adding in cases where index is used instead of group name.

2020-04-07 15:24 UTC, g-lilian commented on src/test/java/seedu/tp/commands/AddFlashcardToGroupCommandTest.java
> +        //Test case1: Given an unionized group name
What does "unionized" mean? O.o

2020-04-08 14:05 UTC, Zhilin-Huang commented on src/test/java/seedu/tp/commands/AddFlashcardToGroupCommandTest.java
> +        //Test case1: Given an unionized group name
Same question haha

2020-04-11 09:47 UTC, Zhilin-Huang requested changes
Remember to also update UG for this change

2020-04-11 09:48 UTC, merged